### ISSUE TITLE
Version Bump?

### ISSUE THREAD

**Issue by steve-gombos** [custom-components/readme#10]
## Version of the custom_component

0.2.1

## Configuration

```yaml

N/A

```

## Describe the bug
Looks like the latest version of HACS was pushed with the data refactor, I assume a new release for this should be published.

## Debug log

```text

N/A

```

**Comment by ludeeus** [comment]
Ups...
@steve-gombos Send you an invite to this repo, you can release if you want :)
Just update <https://github.com/custom-components/readme/blob/master/custom_components/readme/const.py#L5> first

**Comment by edenhaus** [comment]
@ludeeus I think you should release a new version of it otherwise all users must installed the master version, where the versions stays at 0.0.0

**Comment by ludeeus** [comment]
Correct, but i need to test it first

**Comment by ludeeus** [comment]
https://github.com/custom-components/readme/releases/tag/0.3.0
