### ISSUE TITLE
Allow to load / supply variables from yaml 

### ISSUE THREAD

**Issue by tbrasser** [custom-components/readme#17]
**Is your feature request related to a problem? Please describe.**
I use variables declared in yaml for lovelace_gen to generate my dashboards.
I would like to access this data in the templates.

**Describe the solution you'd like**
Either supply the global variables the same way as lovelace_gen does:
something like

```
generate_readme:
  my_vars: !include my_vars.yaml   # normal home-assistant yaml include 

```
**Describe alternatives you've considered**
tried to load variables directly from jinja, but I think you can only import macros that way.

**Additional context**
Actual reason for this is because I want to extend the functionality of this component to parse any .j2 files (or whitelisted) in the config, and want to use the same variables I use for lovelace, this would result in fully templated home assistant readme, config and dashboards.

**Comment by ludeeus** [comment]
Thanks for the suggestion, but this will not be added.
